# Generated by Django 4.2.4 on 2023-09-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ratingAuthor',
            new_name='rating_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentPost',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreation',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryType',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dataCreation',
            new_name='data_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='post_category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category_through',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post_through',
        ),
    ]
