# Generated by Django 4.2.4 on 2023-09-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='category',
        ),
    ]
