# Generated by Django 4.2.5 on 2023-09-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_subscription_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
    ]
